### ISSUE TITLE
The data file missed

### ISSUE THREAD

**Issue by Zhengxinyang** [hansungj/PortoflioOptimization5Models#1]
Hello, I'm studying the portfolio optimization, I think the 'Project2_Data_adjClose.csv' and 'Project2_Data_FF_factors.csv' in this repo are missed. Is it convenient for you to upload those data files?

**Comment by hansungj** [comment]
hey, just uploaded the files please check them out

**Comment by Zhengxinyang** [comment]
Thank you very much!!!
